package com.sciuro.core.ingestion.config

object IngestionDefaults {
    val directBankPackages = setOf(
        "com.cimbmalaysia",
        "my.com.cimb.octo",
        "com.maybank2u.life",
        "com.maybank2u.m2u",
        "com.publicbank.pbebank",
        "com.publicbank.pbepay",
        "my.com.rhb.mymobilebanking",
        "my.com.rhb.mb",
        "my.com.hongleongconnect.mobile.connect",
        "com.ambank.ambonline",
        "com.bankislam.bimbmobile",
        "com.irakyat.mobile",
        "com.bsn.mybsn",
        "my.com.alliancebank.allianceonline",
        "my.com.affinbank.affinonline",
        "com.sc.breeze.malaysia",
        "com.htsu.hsbcpersonalbanking",
        "com.ocbc.mobile",
        "com.uob.mighty.my",
        "com.gxbank.my",
        "com.aeonbank.my",
        "my.com.tngdigital.ewallet",
        "com.grabtaxi.passenger",
        "my.com.myboost",
        "com.shopee.my",
        "my.com.setel",
        "com.bigpay.consumer"
    )

    val aggregatorPackages = setOf(
        "com.google.android.gm",
        "com.microsoft.office.outlook",
        "com.samsung.android.email.provider"
    )

    val defaultAllowedPackages = directBankPackages + aggregatorPackages

    val knownFinanceAppSignatures = mapOf(
        "my.com.maybank.cards" to "Maybank Cards",
        "com.cimbmalaysia.hpbc" to "CIMB BizChannel",
        "com.pbengage.app" to "PB engage",
        "my.com.hongleongconnect.biz" to "HLB Connect Biz",
        "com.rhb.ipay" to "RHB iPay",
        "com.uob.malaysia3d" to "UOB Mighty Secure",
        "com.bankislam.ib" to "Bank Islam IB",
        "com.bsn.cashless" to "BSN Cashless",
        "com.affin.maxmoney" to "Affin MaxMoney",
        "com.alliancebank.oneapp" to "Alliance OneApp",
        "com.shopee.my.wallet" to "ShopeePay",
        "com.grab.pay" to "GrabPay",
        "my.com.touchngo.wallet" to "Touch n Go Wallet",
        "com.lazada.android" to "Lazada",
        "com.wr.boostconnect" to "Boost Connect",
        "my.com.setel.pay" to "Setel Pay",
        "my.com.bigpay.lite" to "BigPay Lite",
        "com.razer.biz" to "Razer Pay",
        "com.alipay.my" to "Alipay MY",
        "com.wechat.malaysia" to "WeChat Pay MY",
        "com.gxbank.biz" to "GX Bank Biz",
        "com.wadiah.app" to "Wadiah",
        "com.kdi.money" to "KDI Money",
        "com.versa.app" to "Versa",
        "com.stashaway.app" to "StashAway",
        "com.wahed.app" to "Wahed Invest",
        "com.fsmone.app" to "FSMOne MY",
        "com.rakutentrade.my" to "Rakuten Trade",
        "com.mplus.my" to "M+ Global",
        "com.luno.bx" to "Luno",
        "com.sinemax.my" to "Sinegy",
        "com.mxglobal.app" to "MX Global",
        "com.helloego.app" to "HelloGold",
        "com.publicmutual.app" to "Public Mutual",
        "com.fsm.rsp" to "FSM PRS",
        "com.prudential.pulse" to "Pulse by Prudential",
        "com.aia.digital" to "AIA Digital",
        "com.greateastern.life" to "Great Eastern",
        "com.uforlife.app" to "U for Life",
        "com.fwd.tapp" to "FWD Tapp",
        "com.etika.app" to "Etika",
        "com.bnm.mybnm" to "BNM MyBNM",
        "com.sc.com.my" to "SC Malaysia",
        "com.ctos.app" to "CTOS",
        "com.ramci.app" to "RAMCI",
        "com.creditbureau.my" to "CCRIS Check",
        "com.duitnow.app" to "DuitNow",
        "com.paynet.app" to "PayNet MY",
        "com.fpx.app" to "FPX",
        "com.jompay.app" to "JomPAY"
    )
}
